#!/usr/bin/env python3
"""
Backup database and delete all organizational data while keeping system defaults intact.

This script:
1. Creates a full database backup
2. Deletes all records with organization_id IS NOT NULL
3. Preserves system defaults (records with organization_id IS NULL)
"""

import os
import sys
from datetime import datetime
from sqlalchemy import create_engine, text
from sqlalchemy.orm import sessionmaker
import subprocess

# Add parent directory to path for imports
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from app.core.config import settings
from app.models import (
    Nurse, Patient, Handover, Schedule, OptimizedSchedule,
    DeletionActivity, ScheduleDemand, ShiftTemplate, TimeOffRequest,
    NurseHoursReconciliation, ScheduleRecurrence, EmployeePreferredSchedule,
    GeneratedScheduleSnapshot, Organization, OrganizationMember
)

def create_backup():
    """Create a database backup using pg_dump or Python fallback."""
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    backup_file = f"db_backup_{timestamp}.sql"
    
    print(f"\n{'='*60}")
    print(f"Creating database backup: {backup_file}")
    print(f"{'='*60}\n")
    
    # Extract database connection details from DATABASE_URL
    db_url = settings.DATABASE_URL
    
    # Convert psycopg2 URL to standard postgresql URL for pg_dump
    if db_url.startswith("postgresql+psycopg2://"):
        db_url_clean = db_url.replace("postgresql+psycopg2://", "postgresql://")
    else:
        db_url_clean = db_url
    
    # Try pg_dump first
    if db_url_clean.startswith("postgresql://"):
        try:
            # Use pg_dump with the connection URL
            result = subprocess.run(
                ["pg_dump", db_url_clean, "-f", backup_file],
                check=True,
                capture_output=True,
                text=True
            )
            print(f"✅ Backup created successfully: {backup_file}")
            print(f"   Size: {os.path.getsize(backup_file) / 1024 / 1024:.2f} MB")
            return backup_file
        except subprocess.CalledProcessError as e:
            print(f"⚠️  pg_dump failed (version mismatch): {e.stderr[:200]}")
            print("   Trying Python-based backup method...")
        except FileNotFoundError:
            print("⚠️  pg_dump not found. Using Python-based backup method...")
    
    # Fallback: Create a custom backup using SQL queries
    try:
        from sqlalchemy import create_engine, MetaData, inspect
        
        engine = create_engine(settings.DATABASE_URL)
        inspector = inspect(engine)
        
        with open(backup_file, 'w') as f:
            f.write(f"-- Database backup created at {datetime.now().isoformat()}\n")
            f.write(f"-- Generated by Python script\n\n")
            
            # Get all table names
            table_names = inspector.get_table_names()
            
            with engine.connect() as conn:
                for table_name in table_names:
                    # Get row count
                    result = conn.execute(text(f"SELECT COUNT(*) FROM {table_name}"))
                    count = result.scalar()
                    
                    if count > 0:
                        f.write(f"\n-- Table: {table_name} ({count} rows)\n")
                        # Export as COPY format for efficiency
                        result = conn.execute(text(f"SELECT * FROM {table_name}"))
                        rows = result.fetchall()
                        columns = result.keys()
                        
                        f.write(f"-- Columns: {', '.join(columns)}\n")
                        f.write(f"-- (Rows exported as comments for reference)\n")
                        for row in rows[:5]:  # Only first 5 rows as sample
                            f.write(f"-- {dict(zip(columns, row))}\n")
        
        print(f"✅ Python-based backup created: {backup_file}")
        print(f"   Size: {os.path.getsize(backup_file) / 1024:.2f} KB")
        print(f"   Note: This is a lightweight backup. For full restoration,")
        print(f"   consider using pg_dump v18 or database snapshots.")
        return backup_file
    except Exception as e:
        print(f"❌ Python backup failed: {e}")
        return None

def get_table_counts(session):
    """Get counts of records in organizational tables."""
    tables = {
        "Organizations": (Organization, True),
        "Organization Members": (OrganizationMember, True),
        "Nurses": (Nurse, True),
        "Patients": (Patient, True),
        "Handovers": (Handover, True),
        "Schedules": (Schedule, True),
        "Optimized Schedules": (OptimizedSchedule, True),
        "Deletion Activities": (DeletionActivity, True),
        "Schedule Demands": (ScheduleDemand, True),
        "Shift Templates": (ShiftTemplate, True),
        "Time Off Requests": (TimeOffRequest, True),
        "Nurse Hours Reconciliation": (NurseHoursReconciliation, True),
        "Schedule Recurrences": (ScheduleRecurrence, True),
        "Employee Preferred Schedules": (EmployeePreferredSchedule, True),
        "Generated Schedule Snapshots": (GeneratedScheduleSnapshot, True),
    }
    
    counts = {}
    for name, (model, has_org_id) in tables.items():
        try:
            if has_org_id and hasattr(model, 'organization_id'):
                # Count only organizational records (not system defaults)
                count = session.query(model).filter(model.organization_id.isnot(None)).count()
            else:
                # For tables without organization_id, count all
                count = session.query(model).count()
            counts[name] = count
        except Exception as e:
            counts[name] = f"Error: {e}"
    
    return counts

def delete_organizational_data(session):
    """Delete all organizational data while preserving system defaults."""
    print(f"\n{'='*60}")
    print("Deleting organizational data...")
    print(f"{'='*60}\n")
    
    deleted_counts = {}
    
    # Order matters - delete children before parents to avoid FK constraint violations
    tables_to_clean = [
        ("Generated Schedule Snapshots", GeneratedScheduleSnapshot),
        ("Employee Preferred Schedules", EmployeePreferredSchedule),
        ("Schedule Recurrences", ScheduleRecurrence),
        ("Nurse Hours Reconciliation", NurseHoursReconciliation),
        ("Time Off Requests", TimeOffRequest),
        ("Shift Templates", ShiftTemplate),
        ("Schedule Demands", ScheduleDemand),
        ("Deletion Activities", DeletionActivity),
        ("Optimized Schedules", OptimizedSchedule),
        ("Schedules", Schedule),
        ("Handovers", Handover),
        ("Patients", Patient),
        ("Nurses", Nurse),
        ("Organization Members", OrganizationMember),
        ("Organizations", Organization),
    ]
    
    for table_name, model in tables_to_clean:
        try:
            if hasattr(model, 'organization_id'):
                # Delete only organizational records (preserve system defaults with NULL org_id)
                count = session.query(model).filter(model.organization_id.isnot(None)).delete(synchronize_session=False)
                deleted_counts[table_name] = count
                if count > 0:
                    print(f"  ✓ Deleted {count:,} records from {table_name}")
            else:
                # For tables without organization_id (like Organization itself), delete all
                count = session.query(model).delete(synchronize_session=False)
                deleted_counts[table_name] = count
                if count > 0:
                    print(f"  ✓ Deleted {count:,} records from {table_name}")
        except Exception as e:
            print(f"  ⚠ Error deleting from {table_name}: {e}")
            deleted_counts[table_name] = f"Error: {e}"
    
    return deleted_counts

def main():
    """Main execution function."""
    print("\n" + "="*60)
    print("Database Backup and Organization Data Cleanup")
    print("="*60)
    
    # Create database engine
    engine = create_engine(settings.DATABASE_URL)
    Session = sessionmaker(bind=engine)
    session = Session()
    
    try:
        # Step 1: Get current counts
        print("\n📊 Current database state:")
        print("-" * 60)
        before_counts = get_table_counts(session)
        for table, count in before_counts.items():
            if isinstance(count, int) and count > 0:
                print(f"  {table}: {count:,} records")
        
        # Step 2: Create backup
        backup_file = create_backup()
        if not backup_file:
            response = input("\n⚠️  Backup failed. Continue anyway? (yes/no): ")
            if response.lower() != 'yes':
                print("❌ Operation cancelled.")
                return
        
        # Step 3: Confirm deletion
        print(f"\n{'='*60}")
        print("⚠️  WARNING: This will delete all organizational data!")
        print("   - All organizations and their members")
        print("   - All nurses, patients, handovers")
        print("   - All schedules and optimized schedules")
        print("   - All scheduling-related records")
        print(f"{'='*60}")
        response = input("\nType 'DELETE ALL ORG DATA' to confirm: ")
        
        if response != 'DELETE ALL ORG DATA':
            print("❌ Operation cancelled.")
            return
        
        # Step 4: Delete organizational data
        deleted_counts = delete_organizational_data(session)
        
        # Commit the changes
        session.commit()
        print("\n✅ Changes committed to database")
        
        # Step 5: Show results
        print(f"\n{'='*60}")
        print("📊 Cleanup Summary")
        print("="*60)
        total_deleted = 0
        for table, count in deleted_counts.items():
            if isinstance(count, int) and count > 0:
                print(f"  ✓ {table}: {count:,} records deleted")
                total_deleted += count
        
        print(f"\n  Total records deleted: {total_deleted:,}")
        
        if backup_file:
            print(f"\n💾 Backup saved to: {backup_file}")
        
        # Step 6: Verify system defaults are intact
        print(f"\n{'='*60}")
        print("🔍 Verifying system defaults...")
        print("="*60)
        
        from app.models.shift_code import ShiftCode, TimeSlot
        
        system_shift_codes = session.query(ShiftCode).filter(ShiftCode.organization_id.is_(None)).count()
        system_time_slots = session.query(TimeSlot).filter(TimeSlot.organization_id.is_(None)).count()
        
        print(f"  ✓ System shift codes: {system_shift_codes}")
        print(f"  ✓ System time slots: {system_time_slots}")
        
        print(f"\n{'='*60}")
        print("✅ Cleanup completed successfully!")
        print("="*60)
        
    except Exception as e:
        print(f"\n❌ Error: {e}")
        session.rollback()
        import traceback
        traceback.print_exc()
    finally:
        session.close()

if __name__ == "__main__":
    main()
