"""add_handover_extended_fields

Revision ID: 2768c1913d4f
Revises: c123456
Create Date: 2026-03-07 17:53:35.264249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2768c1913d4f'
down_revision: Union[str, None] = 'c123456'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('handovers', sa.Column('code_status_manual', sa.String(length=100), nullable=True))
    op.add_column('handovers', sa.Column('revision_date', sa.String(length=50), nullable=True))
    op.add_column('handovers', sa.Column('revision_author', sa.String(length=100), nullable=True))
    op.add_column('handovers', sa.Column('pain_location', sa.String(length=100), nullable=True))
    op.add_column('handovers', sa.Column('pain_relieved_post_med', sa.Text(), nullable=True))
    op.add_column('handovers', sa.Column('pca_checkbox', sa.Boolean(), nullable=True))
    op.add_column('handovers', sa.Column('nca_checkbox', sa.Boolean(), nullable=True))
    op.add_column('handovers', sa.Column('monitoring_cardiac', sa.Boolean(), nullable=True))
    op.add_column('handovers', sa.Column('monitoring_o2_sat', sa.Boolean(), nullable=True))
    op.add_column('handovers', sa.Column('strict_io', sa.Boolean(), nullable=True))
    op.add_column('handovers', sa.Column('urine_ob', sa.String(length=20), nullable=True))
    op.add_column('handovers', sa.Column('urine_ketones', sa.String(length=20), nullable=True))
    op.add_column('handovers', sa.Column('vp_shunt', sa.Boolean(), nullable=True))
    op.add_column('handovers', sa.Column('glasgow_score', sa.String(length=10), nullable=True))
    op.add_column('handovers', sa.Column('oxygen', sa.Text(), nullable=True))
    op.add_column('handovers', sa.Column('cardiovascular', sa.Text(), nullable=True))
    op.add_column('handovers', sa.Column('chest_tube_type_lws', sa.Boolean(), nullable=True))
    op.add_column('handovers', sa.Column('chest_tube_type_sd', sa.Boolean(), nullable=True))
    op.add_column('handovers', sa.Column('vomiting_quantity', sa.String(length=50), nullable=True))
    op.add_column('handovers', sa.Column('last_bowel_movement', sa.String(length=50), nullable=True))
    op.add_column('handovers', sa.Column('constipation', sa.Boolean(), nullable=True))
    op.add_column('handovers', sa.Column('diarrhea', sa.Boolean(), nullable=True))
    op.add_column('handovers', sa.Column('diarrhea_quantity', sa.String(length=50), nullable=True))
    op.add_column('handovers', sa.Column('colostomy', sa.Boolean(), nullable=True))
    op.add_column('handovers', sa.Column('fluid_intake_po', sa.String(length=50), nullable=True))
    op.add_column('handovers', sa.Column('fluid_intake_iv', sa.String(length=50), nullable=True))
    op.add_column('handovers', sa.Column('fluid_intake_ng', sa.String(length=50), nullable=True))
    op.add_column('handovers', sa.Column('weight', sa.String(length=20), nullable=True))
    op.add_column('handovers', sa.Column('formula_checkbox', sa.Boolean(), nullable=True))
    op.add_column('handovers', sa.Column('total_fluid', sa.String(length=50), nullable=True))
    op.add_column('handovers', sa.Column('breast_milk', sa.Boolean(), nullable=True))
    op.add_column('handovers', sa.Column('continuous_feeding', sa.Boolean(), nullable=True))
    op.add_column('handovers', sa.Column('bolus_feeding', sa.Boolean(), nullable=True))
    op.add_column('handovers', sa.Column('bolus_amount', sa.String(length=50), nullable=True))
    op.add_column('handovers', sa.Column('ng_tube', sa.Boolean(), nullable=True))
    op.add_column('handovers', sa.Column('nj_tube', sa.Boolean(), nullable=True))
    op.add_column('handovers', sa.Column('gt_tube', sa.Boolean(), nullable=True))
    op.add_column('handovers', sa.Column('npo', sa.Boolean(), nullable=True))
    op.add_column('handovers', sa.Column('feeding_goal', sa.String(length=100), nullable=True))
    op.add_column('handovers', sa.Column('see_feeding_schedule', sa.Boolean(), nullable=True))
    op.add_column('handovers', sa.Column('skin_assessment', sa.Text(), nullable=True))
    op.add_column('handovers', sa.Column('pressure_sore_stage', sa.String(length=20), nullable=True))
    op.add_column('handovers', sa.Column('pressure_sore_location', sa.String(length=100), nullable=True))
    op.add_column('handovers', sa.Column('pressure_sore_treatment', sa.Text(), nullable=True))
    
    # Use raw SQL with USING clause to convert TEXT to Boolean
    op.execute("ALTER TABLE handovers ALTER COLUMN chest_tube_left TYPE BOOLEAN USING CASE WHEN chest_tube_left IN ('true', 't', 'yes', '1', 'TRUE', 'Yes') THEN TRUE WHEN chest_tube_left IN ('false', 'f', 'no', '0', 'FALSE', 'No', '') THEN FALSE ELSE NULL END")
    op.execute("ALTER TABLE handovers ALTER COLUMN chest_tube_right TYPE BOOLEAN USING CASE WHEN chest_tube_right IN ('true', 't', 'yes', '1', 'TRUE', 'Yes') THEN TRUE WHEN chest_tube_right IN ('false', 'f', 'no', '0', 'FALSE', 'No', '') THEN FALSE ELSE NULL END")
    op.execute("ALTER TABLE handovers ALTER COLUMN vomiting TYPE BOOLEAN USING CASE WHEN vomiting IN ('true', 't', 'yes', '1', 'TRUE', 'Yes') THEN TRUE WHEN vomiting IN ('false', 'f', 'no', '0', 'FALSE', 'No', '') THEN FALSE ELSE NULL END")
    op.alter_column('handovers', 'braden_q_score',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('handovers', 'braden_q_score',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('handovers', 'vomiting',
               existing_type=sa.Boolean(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('handovers', 'chest_tube_right',
               existing_type=sa.Boolean(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('handovers', 'chest_tube_left',
               existing_type=sa.Boolean(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('handovers', 'pressure_sore_treatment')
    op.drop_column('handovers', 'pressure_sore_location')
    op.drop_column('handovers', 'pressure_sore_stage')
    op.drop_column('handovers', 'skin_assessment')
    op.drop_column('handovers', 'see_feeding_schedule')
    op.drop_column('handovers', 'feeding_goal')
    op.drop_column('handovers', 'npo')
    op.drop_column('handovers', 'gt_tube')
    op.drop_column('handovers', 'nj_tube')
    op.drop_column('handovers', 'ng_tube')
    op.drop_column('handovers', 'bolus_amount')
    op.drop_column('handovers', 'bolus_feeding')
    op.drop_column('handovers', 'continuous_feeding')
    op.drop_column('handovers', 'breast_milk')
    op.drop_column('handovers', 'total_fluid')
    op.drop_column('handovers', 'formula_checkbox')
    op.drop_column('handovers', 'weight')
    op.drop_column('handovers', 'fluid_intake_ng')
    op.drop_column('handovers', 'fluid_intake_iv')
    op.drop_column('handovers', 'fluid_intake_po')
    op.drop_column('handovers', 'colostomy')
    op.drop_column('handovers', 'diarrhea_quantity')
    op.drop_column('handovers', 'diarrhea')
    op.drop_column('handovers', 'constipation')
    op.drop_column('handovers', 'last_bowel_movement')
    op.drop_column('handovers', 'vomiting_quantity')
    op.drop_column('handovers', 'chest_tube_type_sd')
    op.drop_column('handovers', 'chest_tube_type_lws')
    op.drop_column('handovers', 'cardiovascular')
    op.drop_column('handovers', 'oxygen')
    op.drop_column('handovers', 'glasgow_score')
    op.drop_column('handovers', 'vp_shunt')
    op.drop_column('handovers', 'urine_ketones')
    op.drop_column('handovers', 'urine_ob')
    op.drop_column('handovers', 'strict_io')
    op.drop_column('handovers', 'monitoring_o2_sat')
    op.drop_column('handovers', 'monitoring_cardiac')
    op.drop_column('handovers', 'nca_checkbox')
    op.drop_column('handovers', 'pca_checkbox')
    op.drop_column('handovers', 'pain_relieved_post_med')
    op.drop_column('handovers', 'pain_location')
    op.drop_column('handovers', 'revision_author')
    op.drop_column('handovers', 'revision_date')
    op.drop_column('handovers', 'code_status_manual')
    # ### end Alembic commands ###
