"""add_age_field_to_patients

Revision ID: 3ec798f94e08
Revises: b8f3a4c5d6e7
Create Date: 2026-03-08 11:57:34.535255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3ec798f94e08'
down_revision: Union[str, None] = 'b8f3a4c5d6e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_handovers_organization'), 'handovers', type_='foreignkey')
    op.alter_column('nurses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('nurses', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_nurses_id'), 'nurses', ['id'], unique=False)
    op.drop_constraint(op.f('fk_nurses_organization'), 'nurses', type_='foreignkey')
    op.add_column('patients', sa.Column('age', sa.String(length=50), nullable=True))
    op.drop_constraint(op.f('fk_patients_organization'), 'patients', type_='foreignkey')
    op.drop_constraint(op.f('fk_schedules_organization'), 'schedules', type_='foreignkey')
    op.drop_index(op.f('ix_system_prompts_organization_id'), table_name='system_prompts')
    op.drop_constraint(op.f('fk_system_prompts_organization'), 'system_prompts', type_='foreignkey')
    op.drop_column('system_prompts', 'organization_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_prompts', sa.Column('organization_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_system_prompts_organization'), 'system_prompts', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_system_prompts_organization_id'), 'system_prompts', ['organization_id'], unique=False)
    op.create_foreign_key(op.f('fk_schedules_organization'), 'schedules', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_patients_organization'), 'patients', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.drop_column('patients', 'age')
    op.create_foreign_key(op.f('fk_nurses_organization'), 'nurses', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_nurses_id'), table_name='nurses')
    op.alter_column('nurses', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('nurses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_foreign_key(op.f('fk_handovers_organization'), 'handovers', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
