"""add_seniority_field_to_nurses

Revision ID: 699d1ed2fe5b
Revises: c738afb7118b
Create Date: 2026-03-10 19:12:02.656400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '699d1ed2fe5b'
down_revision: Union[str, None] = 'c738afb7118b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nurses', sa.Column('seniority', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nurses', 'seniority')
    # ### end Alembic commands ###
