"""make schedule_id nullable in optimized_schedules

Revision ID: 6a5933d98ad5
Revises: 2768c1913d4f
Create Date: 2026-03-07 20:13:11.601266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a5933d98ad5'
down_revision: Union[str, None] = '2768c1913d4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('optimized_schedules', 'schedule_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('optimized_schedules', 'schedule_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
