"""add system_prompt table

Revision ID: a794836b7dfa
Revises: 891a861393c6
Create Date: 2025-05-31 16:09:02.773181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a794836b7dfa'
down_revision: Union[str, None] = '891a861393c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_prompts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_prompts_id'), 'system_prompts', ['id'], unique=False)
    op.create_index(op.f('ix_system_prompts_name'), 'system_prompts', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_prompts_name'), table_name='system_prompts')
    op.drop_index(op.f('ix_system_prompts_id'), table_name='system_prompts')
    op.drop_table('system_prompts')
    # ### end Alembic commands ###
