"""add_patient_and_handover_tables

Revision ID: c90e2ba6621b
Revises: a794836b7dfa
Create Date: 2026-03-07 13:33:15.444413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c90e2ba6621b'
down_revision: Union[str, None] = 'a794836b7dfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('mrn', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('room_number', sa.String(length=20), nullable=False),
    sa.Column('bed', sa.String(length=10), nullable=True),
    sa.Column('diagnosis', sa.String(length=255), nullable=True),
    sa.Column('attending_physician', sa.String(length=100), nullable=True),
    sa.Column('admission_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_mrn'), 'patients', ['mrn'], unique=False)
    op.create_table('schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('rules', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('raw_images', sa.JSON(), nullable=True),
    sa.Column('employee_comments', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('handovers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('shift_date', sa.DateTime(), nullable=False),
    sa.Column('shift_type', sa.String(length=20), nullable=False),
    sa.Column('outgoing_nurse', sa.String(length=100), nullable=False),
    sa.Column('incoming_nurse', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('STABLE', 'IMPROVED', 'UNCHANGED', 'WORSENING', 'CRITICAL', name='patientstatus'), nullable=True),
    sa.Column('acuity', sa.Enum('LOW', 'MODERATE', 'HIGH', 'CRITICAL', name='acuitylevel'), nullable=True),
    sa.Column('isolation', sa.Enum('NONE', 'CONTACT', 'DROPLET', 'AIRBORNE', 'NEUTROPENIC', 'PROTECTIVE', name='isolationtype'), nullable=True),
    sa.Column('code_status', sa.String(length=50), nullable=True),
    sa.Column('allergies', sa.Text(), nullable=True),
    sa.Column('iv_access', sa.Text(), nullable=True),
    sa.Column('medications_summary', sa.Text(), nullable=True),
    sa.Column('events_this_shift', sa.Text(), nullable=True),
    sa.Column('pending_tasks', sa.Text(), nullable=True),
    sa.Column('pending_labs', sa.Text(), nullable=True),
    sa.Column('consults', sa.Text(), nullable=True),
    sa.Column('diet', sa.String(length=100), nullable=True),
    sa.Column('activity', sa.String(length=100), nullable=True),
    sa.Column('pain_notes', sa.Text(), nullable=True),
    sa.Column('family_notes', sa.Text(), nullable=True),
    sa.Column('additional_notes', sa.Text(), nullable=True),
    sa.Column('voice_transcription', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_draft', sa.Boolean(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('optimized_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('schedule_id', sa.UUID(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('finalized', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('optimized_schedules')
    op.drop_table('handovers')
    op.drop_table('users')
    op.drop_table('schedules')
    op.drop_index(op.f('ix_patients_mrn'), table_name='patients')
    op.drop_table('patients')
    # ### end Alembic commands ###
