"""add_gu_interval_fields

Revision ID: d0155a56d5bd
Revises: e479727c53bb
Create Date: 2026-03-07 22:47:44.511934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0155a56d5bd'
down_revision: Union[str, None] = 'e479727c53bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('handovers', sa.Column('io_interval', sa.String(length=10), nullable=True))
    op.add_column('handovers', sa.Column('io_00_last6h', sa.String(length=50), nullable=True))
    op.add_column('handovers', sa.Column('io_06_last6h', sa.String(length=50), nullable=True))
    op.add_column('handovers', sa.Column('io_12_last6h', sa.String(length=50), nullable=True))
    op.add_column('handovers', sa.Column('io_18_last6h', sa.String(length=50), nullable=True))
    op.add_column('handovers', sa.Column('io_00_04', sa.String(length=50), nullable=True))
    op.add_column('handovers', sa.Column('io_00_04_last6h', sa.String(length=50), nullable=True))
    op.add_column('handovers', sa.Column('io_04_08', sa.String(length=50), nullable=True))
    op.add_column('handovers', sa.Column('io_04_08_last6h', sa.String(length=50), nullable=True))
    op.add_column('handovers', sa.Column('io_08_12', sa.String(length=50), nullable=True))
    op.add_column('handovers', sa.Column('io_08_12_last6h', sa.String(length=50), nullable=True))
    op.add_column('handovers', sa.Column('io_12_16', sa.String(length=50), nullable=True))
    op.add_column('handovers', sa.Column('io_12_16_last6h', sa.String(length=50), nullable=True))
    op.add_column('handovers', sa.Column('io_16_20', sa.String(length=50), nullable=True))
    op.add_column('handovers', sa.Column('io_16_20_last6h', sa.String(length=50), nullable=True))
    op.add_column('handovers', sa.Column('io_20_24', sa.String(length=50), nullable=True))
    op.add_column('handovers', sa.Column('io_20_24_last6h', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('handovers', 'io_20_24_last6h')
    op.drop_column('handovers', 'io_20_24')
    op.drop_column('handovers', 'io_16_20_last6h')
    op.drop_column('handovers', 'io_16_20')
    op.drop_column('handovers', 'io_12_16_last6h')
    op.drop_column('handovers', 'io_12_16')
    op.drop_column('handovers', 'io_08_12_last6h')
    op.drop_column('handovers', 'io_08_12')
    op.drop_column('handovers', 'io_04_08_last6h')
    op.drop_column('handovers', 'io_04_08')
    op.drop_column('handovers', 'io_00_04_last6h')
    op.drop_column('handovers', 'io_00_04')
    op.drop_column('handovers', 'io_18_last6h')
    op.drop_column('handovers', 'io_12_last6h')
    op.drop_column('handovers', 'io_06_last6h')
    op.drop_column('handovers', 'io_00_last6h')
    op.drop_column('handovers', 'io_interval')
    # ### end Alembic commands ###
